services:

  laravel-docker:
    container_name: netflix-clone
    build: .
    volumes:
      - ./netflix-clone:/var/www/html
    ports:
      - 9000:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netflix-clone
    ports:
    - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./netflix-clone/scripts:/scripts
      - ./netflix-clone/backups:/backups
      - ./netflix-clone/.env:/var/www/html/.env
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

  backup_service:
    build:
      context: .
      dockerfile: backup.Dockerfile
    container_name: backup_service
    volumes:
      - ./netflix-clone:/var/www/html
      - ./netflix-clone/backups:/backups
    depends_on:
      - mysql_db

volumes:
  db_data: