services:
  mariadb:
    image: mariadb:latest
    container_name: netflix-clone-mariadb
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: netflix-clone-phpmyadmin
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mariadb

  laravel:
    build:
      context: .
      dockerfile: ./netflix-clone/Dockerfile
    container_name: netflix-clone-laravel
    platform: linux/amd64
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./netflix-clone:/var/www/html:z
    command: >
      sh /var/www/html/entrypoint.sh

volumes:
  mariadb-data: